# Generated by Django 3.0.6 on 2020-06-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmjumbe',
            name='id_card',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tempmjumbe',
            name='id_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tempmjumbe',
            name='kata',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tempmjumbe',
            name='kitongoji',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tempmjumbe',
            name='mtaa_kijiji',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tempmjumbe',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tempmjumbe',
            name='pin',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tempmjumbe',
            name='shina',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tempveo',
            name='id_card',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tempveo',
            name='id_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tempveo',
            name='kata',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tempveo',
            name='mtaa_kijiji',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tempveo',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tempveo',
            name='pin',
            field=models.IntegerField(null=True),
        ),
    ]
