# Generated by Django 3.0.6 on 2020-05-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedmessages',
            name='recipient',
            field=models.CharField(blank=True, default='System', max_length=13),
        ),
        migrations.AlterField(
            model_name='sentmessages',
            name='sender',
            field=models.CharField(blank=True, default='System', max_length=13),
        ),
    ]
