# Generated by Django 3.0.6 on 2020-05-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0003_auto_20200526_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentmessages',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
