# Generated by Django 3.0.6 on 2020-06-19 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0003_keywordmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordmessage',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
