# Generated by Django 3.0.6 on 2020-06-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0004_auto_20200526_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('statement', models.TextField()),
                ('steps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mwananchi',
            fields=[
                ('mnc_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('mnc_phone', models.CharField(max_length=13, unique=True)),
                ('mnc_name', models.CharField(max_length=50)),
                ('mnc_occupation', models.CharField(max_length=50)),
                ('mnc_kitongoji', models.CharField(max_length=50)),
                ('mnc_mtaa_kijiji', models.CharField(max_length=50)),
                ('mnc_kata', models.CharField(max_length=50)),
                ('mnc_id_card', models.CharField(max_length=50)),
                ('mnc_id_number', models.IntegerField(unique=True)),
                ('mnc_pin', models.IntegerField()),
                ('mnc_date_time', models.DateTimeField(auto_now_add=True)),
                ('mnc_step', models.IntegerField()),
                ('mnc_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('mnc_id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('mnc_phone', models.CharField(max_length=13, unique=True)),
                ('mnc_name', models.CharField(max_length=50, null=True)),
                ('mnc_occupation', models.CharField(max_length=50, null=True)),
                ('mnc_kitongoji', models.CharField(max_length=50, null=True)),
                ('mnc_mtaa_kijiji', models.CharField(max_length=50, null=True)),
                ('mnc_kata', models.CharField(max_length=50, null=True)),
                ('mnc_id_card', models.CharField(max_length=50, null=True)),
                ('mnc_id_number', models.IntegerField(null=True, unique=True)),
                ('mnc_pin', models.IntegerField(null=True)),
                ('mnc_date_time', models.DateTimeField(auto_now_add=True)),
                ('mnc_step', models.IntegerField()),
                ('mnc_status', models.CharField(max_length=50)),
            ],
        ),
    ]
