# Generated by Django 3.0.6 on 2020-06-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0004_auto_20200526_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mwananchi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnc_name', models.CharField(max_length=50)),
                ('mnc_phone', models.CharField(max_length=13)),
                ('mnc_occupation', models.CharField(max_length=50)),
                ('mnc_kitongoji', models.CharField(max_length=50)),
                ('mnc_mtaa_kijiji', models.CharField(max_length=50)),
                ('mnc_kata', models.CharField(max_length=50)),
                ('mnc_id', models.CharField(max_length=50)),
                ('mnc_id_number', models.IntegerField()),
                ('mnc_pin', models.IntegerField()),
                ('mnc_date_time', models.DateTimeField(auto_now_add=True)),
                ('mnc_status', models.CharField(max_length=50)),
                ('mnc_step', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnc_name', models.CharField(max_length=50)),
                ('mnc_phone', models.CharField(max_length=13)),
                ('mnc_occupation', models.CharField(max_length=50)),
                ('mnc_kitongoji', models.CharField(max_length=50)),
                ('mnc_mtaa_kijiji', models.CharField(max_length=50)),
                ('mnc_kata', models.CharField(max_length=50)),
                ('mnc_id', models.CharField(max_length=50)),
                ('mnc_id_number', models.IntegerField()),
                ('mnc_pin', models.IntegerField()),
                ('mnc_date_time', models.DateTimeField(auto_now_add=True)),
                ('mnc_status', models.CharField(max_length=50)),
                ('mnc_step', models.IntegerField()),
            ],
        ),
    ]
