# Generated by Django 3.0.6 on 2020-06-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0004_keywordmessage_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_postcode', models.IntegerField()),
                ('district', models.CharField(max_length=200)),
                ('district_postcode', models.CharField(max_length=200)),
                ('ward', models.CharField(max_length=200)),
                ('ward_postcode', models.CharField(max_length=200)),
                ('old_ward_postcode', models.CharField(max_length=200)),
                ('mtaa_kijiji', models.CharField(max_length=200)),
                ('kitongoji', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
