# Generated by Django 3.0.6 on 2020-06-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0005_mwananchi_tempuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('statement', models.TextField()),
                ('steps', models.IntegerField()),
            ],
        ),
    ]
