# Generated by Django 3.0.6 on 2020-06-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0005_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mwenyekiti',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('mtaa_kijiji', models.CharField(max_length=200)),
                ('kata', models.CharField(max_length=200)),
                ('id_card', models.CharField(max_length=20)),
                ('id_number', models.IntegerField(unique=True)),
                ('pin', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('step', models.IntegerField()),
                ('is_active', models.CharField(max_length=20)),
                ('verification_status', models.CharField(max_length=20)),
                ('weo_id', models.CharField(max_length=13, null=True)),
                ('date_weo_verified', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempMwenyekiti',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('mtaa_kijiji', models.CharField(max_length=200, null=True)),
                ('kata', models.CharField(max_length=200, null=True)),
                ('id_card', models.CharField(max_length=20, null=True)),
                ('id_number', models.IntegerField(null=True, unique=True)),
                ('pin', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('step', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
