# Generated by Django 3.0.6 on 2020-06-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0007_auto_20200628_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='date_used',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
