# Generated by Django 3.0.6 on 2020-06-28 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0008_auto_20200629_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
