# Generated by Django 3.0.6 on 2020-07-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jihakiki', '0009_auto_20200629_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barua',
            old_name='reference',
            new_name='reference_number',
        ),
        migrations.AddField(
            model_name='barua',
            name='step',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keywordmessage',
            name='section',
            field=models.CharField(default='Null', max_length=20),
            preserve_default=False,
        ),
    ]
